services:
  - type: web
    name: huawei-ict-platform
    env: docker
    plan: free
    branch: main
    repo: https://github.com/Lvyc592/huawei-ict-platform
    buildCommand: ""
    startCommand: ""
envVars:
  - key: SPRING_PROFILES_ACTIVE
    value: prod
  - key: JWT_SECRET
    value: mySecretKey123456789012345678901234567890
